### PR TITLE
Scan content from publicly accessible PDF documentation files

### PR DESCRIPTION
**Pull request by fjuma**
Note that running this takes a few minutes since there are a bunch of PDFs that are being ingested.

### CODE REVIEW

**Comment by scottmarlow** [comment]
Nice work Farah!  Looks good to me!

**Comment by fjuma** [comment]
Added a second commit that updates the prompt and also outputs information about the PDF files (names and page numbers) that were used to answer the question.

**Comment by fjuma** [comment]
Also added a simple text file with some security best practices. I'm not making use of this right now but tried doing so and have added some comments about this in the google doc.

**Comment by fl4via** [comment]
> Added a second commit that updates the prompt and also outputs information about the PDF files (names and page numbers) that were used to answer the question.

I gave it a try and it works great @fjuma

**Pull request merged**
